### ISSUE TITLE
Starting with pi-spio bug

### ISSUE THREAD

**Issue by Gentlehag** [rakeshpai/pi-gpio#28]
I've the following code on a rapsberry pi

when starting with sudo node app.js i got the following error

/home/pi/dev/PiIde/app.js:7
    if(err) throw err;

i must say that in t his first thest i don't have anything connected to the gpio.

is this an expected behavior ? 

app.js:
```javascript
var http = require('http');
var gpio = require("pi-gpio");

http.createServer(function (req, res) {

  gpio.read(16, function(err, value) {
    if(err) throw err;
    console.log(value);    // The current state of the pin
});

  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\n');
}).listen(1337);
console.log('Server running at http://127.0.0.1:1337/');
```

**Comment by tjanson** [comment]
Closing as stale, please reopen if issue still occurs.
