### ISSUE TITLE
correct quick2wire-gpio-admin/src/gpio-admin.c

### ISSUE THREAD

**Issue by alex-dacosta** [rakeshpai/pi-gpio#46]
likewise you should correct it also adding:
`#define GPIO_ACCESS_PATH (GPIO_CLASS_PATH "/gpio%u/%s")`
and modifying
`int size = snprintf(path, PATH_MAX, GPIO_ACCESS_PATH, pin, filename);`

**Comment by tjanson** [comment]
You’re right, but quick2wire is upstream.
